[package]
name = "verlet-process"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-trait = { workspace = true }
verlet-abi = { path = "../verlet-abi" }
verlet-runtime-contracts = { path = "../verlet-runtime-contracts" }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "process", "sync", "time"] }
tokio-util = { workspace = true }
uuid = { workspace = true, features = ["serde", "v7"] }
strum.workspace = true

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
