[package]
name = "verlet-io-telegram"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
verlet-io-core = { path = "../verlet-io-core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
