<script lang="ts">
  import {
    Activity,
    Boxes,
    Cpu,
    FolderTree,
    MessagesSquare,
    Search,
    Plug,
    Power,
    RefreshCw,
    Plus,
    X,
    PanelLeft,
    PanelRight,
    PanelBottom,
    Send,
    Square,
    Terminal,
    Command,
    ChevronsUpDown,
    CircleDot,
    Folder,
    FileCode,
    Rocket,
    Globe,
    MonitorSmartphone,
    Zap,
    Filter,
    CornerDownLeft,
    Inbox,
    GitBranch,
    Server,
    Settings,
    Palette,
    Wifi,
    Keyboard,
    Info,
    Sparkles,
    Wrench,
    Bot,
    Brain,
    Library,
    ArrowUpRight,
    Cable,
    ChevronDown,
    ChevronRight,
    CirclePause,
    Cloud,
    Download,
    FileText,
    HardDrive,
    KeyRound,
    LogOut,
    Play,
    RefreshCcw,
    Trash2,
    TriangleAlert,
    type Icon as IconType,
  } from "lucide-svelte";

  const map: Record<string, typeof IconType> = {
    Activity,
    Boxes,
    Cpu,
    FolderTree,
    MessagesSquare,
    Search,
    Plug,
    Power,
    RefreshCw,
    Plus,
    X,
    PanelLeft,
    PanelRight,
    PanelBottom,
    Send,
    Square,
    Terminal,
    Command,
    ChevronsUpDown,
    CircleDot,
    Folder,
    FileCode,
    Rocket,
    Globe,
    MonitorSmartphone,
    Zap,
    Filter,
    CornerDownLeft,
    Inbox,
    GitBranch,
    Server,
    Settings,
    Palette,
    Wifi,
    Keyboard,
    Info,
    Sparkles,
    Wrench,
    Bot,
    Brain,
    Library,
    ArrowUpRight,
    Cable,
    ChevronDown,
    ChevronRight,
    CirclePause,
    Cloud,
    Download,
    FileText,
    HardDrive,
    KeyRound,
    LogOut,
    Play,
    RefreshCcw,
    Trash2,
    TriangleAlert,
  };

  let {
    name,
    size = 16,
    strokeWidth = 2,
    class: className = "",
  }: { name: string; size?: number; strokeWidth?: number; class?: string } = $props();
  const Cmp = $derived(map[name] ?? CircleDot);
</script>

<Cmp {size} {strokeWidth} class={className} />
