[package]
name = "verlet-chat"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
crossterm = { workspace = true }
futures-util = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
tuika = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
