[package]
name = "verlet-history-sqlite"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-trait = { workspace = true }
verlet-history = { path = "../verlet-history" }
verlet-runtime-contracts = { path = "../verlet-runtime-contracts" }
verlet-sqlite = { path = "../verlet-sqlite" }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
base64 = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
