#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source_url=${1:-https://models.dev/api.json}
snapshot="$repo_root/crates/verlet-kernel/data/model-catalog.json"
snapshot_dir=$(dirname "$snapshot")

for command_name in curl jq; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "update-model-catalog: required command not found: $command_name" >&2
    exit 1
  fi
done

mkdir -p "$snapshot_dir"
upstream=$(mktemp "${TMPDIR:-/tmp}/verlet-model-catalog.XXXXXX")
generated=$(mktemp "$snapshot_dir/.model-catalog.json.XXXXXX")
cleanup() {
  rm -f "$upstream" "$generated"
}
trap cleanup EXIT

curl --fail --silent --show-error --location \
  --connect-timeout 5 --max-time 30 \
  "$source_url" --output "$upstream"

jq '
  def normalized_model($provider_id; $entry):
    {
      provider_id: $provider_id,
      model_id: ($entry.value.id // $entry.key),
      display_name: ($entry.value.name // $entry.value.id // $entry.key)
    }
    + (if $entry.value.limit.context != null
       then {context_window: $entry.value.limit.context} else {} end)
    + (if $entry.value.limit.output != null
       then {max_output_tokens: $entry.value.limit.output} else {} end)
    + (if $entry.value.cost.input != null
       then {input_price: $entry.value.cost.input} else {} end)
    + (if $entry.value.cost.output != null
       then {output_price: $entry.value.cost.output} else {} end)
    + {
      reasoning: ($entry.value.reasoning // false),
      deprecated: (($entry.value.status // "") == "deprecated")
    };

  def is_openai_codex_model:
    ascii_downcase as $id
    | ($id | contains("codex"))
      or $id == "gpt-5.6-sol"
      or $id == "gpt-5.6-terra";

  . as $root
  | {
      "_comment": "Generated by scripts/update-model-catalog.sh from models.dev; do not edit by hand.",
      models: (
        [
          (($root.anthropic.models // {}) | to_entries[]
            | normalized_model("anthropic"; .)),
          (($root.openai.models // {}) | to_entries[]
            | normalized_model("openai"; .)),
          (($root.openai.models // {}) | to_entries[]
            | select((.value.id // .key) | is_openai_codex_model)
            | normalized_model("openai-codex"; .))
        ]
        | sort_by(.provider_id, .model_id)
      )
    }
' "$upstream" >"$generated"

mv "$generated" "$snapshot"
trap - EXIT
rm -f "$upstream"
