#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source_url=${1:-https://models.dev/api.json}
snapshot="$repo_root/crates/verlet-kernel/data/model-catalog.json"
snapshot_dir=$(dirname "$snapshot")

for command_name in curl jq; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "update-model-catalog: required command not found: $command_name" >&2
    exit 1
  fi
done

mkdir -p "$snapshot_dir"
upstream=$(mktemp "${TMPDIR:-/tmp}/verlet-model-catalog.XXXXXX")
generated=$(mktemp "$snapshot_dir/.model-catalog.json.XXXXXX")
cleanup() {
  rm -f "$upstream" "$generated"
}
trap cleanup EXIT

curl --fail --silent --show-error --location \
  --connect-timeout 5 --max-time 30 --max-filesize 8388608 \
  --output "$upstream" -- "$source_url"

jq -e '
  def nonempty_string:
    select(type == "string") | gsub("^\\s+|\\s+$"; "") | select(length > 0);

  def positive_integer:
    select(type == "number" and . > 0 and floor == .);

  def nonnegative_number:
    select(type == "number" and . >= 0);

  def normalized_model($provider_id; $entry):
    ($entry.value | select(type == "object")) as $model
    | (($model.id | nonempty_string) // ($entry.key | nonempty_string)) as $model_id
    | (($model.name | nonempty_string) // $model_id) as $display_name
    | (($model.limit.context | positive_integer) // null) as $context_window
    | (($model.limit.output | positive_integer) // null) as $max_output_tokens
    | (($model.cost.input | nonnegative_number) // null) as $input_price
    | (($model.cost.output | nonnegative_number) // null) as $output_price
    | {
      provider_id: $provider_id,
      model_id: $model_id,
      display_name: $display_name
    }
    + (if $context_window != null
       then {context_window: $context_window} else {} end)
    + (if $max_output_tokens != null
       then {max_output_tokens: $max_output_tokens} else {} end)
    + (if $input_price != null
       then {input_price: $input_price} else {} end)
    + (if $output_price != null
       then {output_price: $output_price} else {} end)
    + {
      reasoning: ($model.reasoning == true),
      deprecated: (($model.status // "") == "deprecated")
    };

  def model_entries($root; $provider_id):
    ($root[$provider_id].models // {})
    | select(type == "object")
    | to_entries[];

  def is_openai_codex_model:
    ascii_downcase as $id
    | ($id | contains("codex"))
      or $id == "gpt-5.6-sol"
      or $id == "gpt-5.6-terra";

  select(type == "object") as $root
  | {
      "_comment": "Generated by scripts/update-model-catalog.sh from models.dev; do not edit by hand.",
      models: (
        [
          (model_entries($root; "anthropic")
            | normalized_model("anthropic"; .)),
          (model_entries($root; "openai")
            | normalized_model("openai"; .)),
          (model_entries($root; "openai")
            | normalized_model("openai-codex"; .)
            | select(.model_id | is_openai_codex_model))
        ]
        | sort_by(.provider_id, .model_id)
        | unique_by(.provider_id, .model_id)
      )
    }
  | select(.models | length > 0)
' "$upstream" >"$generated"

chmod 0644 "$generated"
mv "$generated" "$snapshot"
trap - EXIT
rm -f "$upstream"
